import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { IRoute, Navbar } from './components/navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const homeRoutes: IRoute[] = [
  { url: '/', text: 'Home' },
  { url: '/projects', text: 'Projects' },
  { url: '/contacts', text: 'Contacts' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar routes={homeRoutes} />
        </header>
        {children}
      </body>
    </html>
  );
}
